# If running this app locally, these requests can be used via VSCode's
# REST Client to test the api.
# Replace 'your_api_key_here' with your api key.
# DO NOT USE QUOTATION MARKS!
@apikey = your_api_key_here

# GET todos
# all

GET http://localhost:8080/api/todos?apikey={{apikey}}

###
# one

GET http://localhost:8080/api/todos/1?apikey={{apikey}}

###
# how about a non-existing one?

GET http://localhost:8080/api/todos/999?apikey={{apikey}}

###
# pagination!

GET http://localhost:8080/api/todos?limit=5&offset=3&apikey={{apikey}}

###
# filtering!
# is_done (bool)
GET http://localhost:8080/api/todos?is_done=true&apikey={{apikey}}

###
# priority (number)
GET http://localhost:8080/api/todos?priority=1&apikey={{apikey}}

###
# listid (number)
GET http://localhost:8080/api/todos?listid=2&apikey={{apikey}}

###
# or a combination of the above
GET http://localhost:8080/api/todos?listid=1&priority=1&apikey={{apikey}}

###
# Single column Sorting!
# name (asc)
GET http://localhost:8080/api/todos?sort=name:asc&apikey={{apikey}}

###
# name (desc)
GET http://localhost:8080/api/todos?sort=name:desc&apikey={{apikey}}

###
# date (asc)
GET http://localhost:8080/api/todos?sort=date_created:asc&apikey={{apikey}}

###
# date (desc)
GET http://localhost:8080/api/todos?sort=date_created:desc&apikey={{apikey}}

###
# priority (asc)
GET http://localhost:8080/api/todos?sort=priority:asc&apikey={{apikey}}

###
# priority (desc)
GET http://localhost:8080/api/todos?sort=priority:desc&apikey={{apikey}}

###
# date_deadline (asc)
GET http://localhost:8080/api/todos?sort=date_deadline:asc&apikey={{apikey}}

###
# date_deadline (desc)
GET http://localhost:8080/api/todos?sort=date_deadline:desc&apikey={{apikey}}

### Sorting failure
# trying to sort a non existent column:
GET http://localhost:8080/api/todos?sort=gojira:desc&apikey={{apikey}}


###
# POST todos
# date_created is automatically generated
# listid has to point to an existing list!

# all fields

POST http://localhost:8080/api/todos?apikey={{apikey}}
Content-Type: application/json

{
  "date_deadline": "2020-11-20",
  "name": "This is a test task",
  "description": "description",
  "priority": 1,
  "is_done": false,
  "listid": 1
}

###
# only required fields

POST http://localhost:8080/api/todos?apikey={{apikey}}
Content-Type: application/json

{
  "name": "This is another test task",
  "listid": 2
}

###
# one that fails

POST http://localhost:8080/api/todos?apikey={{apikey}}
Content-Type: application/json

{
  "date_deadline": "2020-11-21",
  "name": null,
  "description": "description",
  "priority": 2,
  "listid": 1
}

###
# another one just because

POST http://localhost:8080/api/todos?apikey={{apikey}}
Content-Type: application/json

{
  "date_deadline": "2020-11-21",
  "name": "Doesn't work",
  "description": "description",
  "priority": 2,
  "listid": 100
}

###

# PUT todos

###
# here's a quick GET to see how it looks
# before update
GET http://localhost:8080/api/todos/4?apikey={{apikey}}

###
# update an existing todo
PUT http://localhost:8080/api/todos/4?apikey={{apikey}}
Content-Type: application/json

{
  "date_created": "2020-11-25",
  "date_deadline": "2020-11-25",
  "name": "Pest control yep",
  "description": "Nothing to see here :)",
  "priority": 3,
  "is_done": true,
  "listid": 2
}

###
# no need to specify everything, only the changed
# field(s)

PUT http://localhost:8080/api/todos/4?apikey={{apikey}}
Content-Type: application/json

{
  "name": "Pest control"
}

###

# DELETE todos
# by id

DELETE http://localhost:8080/api/todos/1?apikey={{apikey}}

###
# can't delete everything though

DELETE http://localhost:8080/api/todos?apikey={{apikey}}

###

# same but for lists

# GET lists
# all

GET http://localhost:8080/api/lists?apikey={{apikey}}

###
# one

GET http://localhost:8080/api/lists/1?apikey={{apikey}}

###
# POST lists

POST http://localhost:8080/api/lists?apikey={{apikey}}
Content-Type: application/json

{
  "name": "chores"
}

###
# PUT lists
# update an existing list

PUT http://localhost:8080/api/lists/1?apikey={{apikey}}
Content-Type: application/json

{
  "name": "Pest control"
}

###
# DELETE lists
# by id

DELETE http://localhost:8080/api/lists/1?apikey={{apikey}}

###
# can't delete everything

DELETE http://localhost:8080/api/lists?apikey={{apikey}}

###
